### PR TITLE
Added typescript definition for zero-fill

### PR DESCRIPTION
**Pull request by Loupax**
Could not use zero-fill in my typescript project unless I created the definitions for the function. Have a look and see if it works for you :)

### CODE REVIEW

**Comment by Loupax** [comment]
Rushed it a bit, will reopen it once I get the warnings fixed

**Comment by maiermic** [comment]
I've used the type definition successful, too. Thanks @Loupax :+1: 

@feross Please merge this pull request (warnings are fixed).

**Comment by feross** [comment]
Sorry, I don't use Typescript so this is an extra maintenance burden for me. This file will get out of sync with the code over time unless someone keeps it up to date.

**Comment by Loupax** [comment]
No problem :)

**Pull request closed without merging**
